name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # # == CHECK == #
  # check:
  #   name: Check nightly beta stable and MSRV
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       rust-toolchains:
  #         - 1.42.0
  #         - stable
  #         - beta
  #   steps:
  #     - name: Install Rust toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: ${{ matrix.rust-toolchains }}
  #         override: true

  #     - name: Clone repo
  #       uses: actions/checkout@v2

  #     - name: Cargo check
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: check

  # # == BUILD & TEST == #
  # build-and-test:
  #   name: Build and test
  #   runs-on: ${{ matrix.os }}
  #   needs: [check]
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         - macos-latest
  #         - windows-latest
  #       rust-toolchains:
  #         - 1.42.0
  #         - stable
  #   steps:
  #     - name: Install Rust toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         profile: default
  #         override: true
  #         toolchain: ${{ matrix.rust-toolchains }}

  #     - name: Clone repo
  #       uses: actions/checkout@v2

  #     - name: Cargo test
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: test

  # == MIRI == #
  miri:
    name: Test with miri
    runs-on: [ubuntu-latest]
    # needs: [check]
    steps:
      # - name: Install Rust toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     profile: minimal
      #     override: false
      #     toolchain: nightly

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Test with miri
        run: ./miri_test.sh

      # - name: Cargo test
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: miri test
